from django.http import JsonResponse, HttpResponseBadRequest, HttpResponseForbidden  # [added]
from django.views.decorators.http import require_GET, require_POST  # [added]
from django.views.decorators.csrf import csrf_exempt  # [added]
from django.conf import settings  # [added]
from django.shortcuts import get_object_or_404  # [added]
from decimal import Decimal  # [added]
import json  # [added]

from .models import Order  # [added]
from templates.models import Template  # [added]


SESSION_TEMPLATE_KEY = 'basket_template'  # [added]


def _money(amount: Decimal, currency: str):  # [added]
    return { 'amount': f"{amount:.2f}", 'currency': currency }  # [added]


def _get_or_create_draft_order(user):  # [added]
    if not user.is_authenticated or not hasattr(user, 'customer_profile') or not user.customer_profile:  # [added]
        return None  # [added]
    customer = user.customer_profile  # [added]
    order = Order.objects.filter(customer=customer, status=Order.StatusChoices.PENDING).order_by('-created_at').first()  # [added]
    if not order:  # [added]
        order = Order.objects.create(customer=customer, status=Order.StatusChoices.PENDING, currency=getattr(settings, 'DEFAULT_CURRENCY', 'EUR'))  # [added]
    return order  # [added]


def _compute_template_pricing(tpl: Template, guest_count: int):  # [added]
    # Business rule: subtotal = base_price + max(0, guests - default_guests) * price_per_additional_guest  # [added]
    additional = max(0, guest_count - (tpl.default_guests or 0))  # [added]
    subtotal = (tpl.base_price or Decimal('0.00')) + (Decimal(additional) * (tpl.price_per_additional_guest or Decimal('0.00')))  # [added]
    unit = subtotal / Decimal(max(guest_count, 1))  # [added]
    return unit, subtotal  # [added]


def _basket_from(order: Order, session_template: dict | None):  # [added]
    currency = session_template['currency'] if session_template else order.currency  # [added]
    template_obj = session_template if session_template else None  # [added]
    totals = {  # [added]
        'template_total': _money(Decimal(session_template['subtotal']['amount']) if session_template else Decimal('0.00'), currency),  # [added]
        'services_total': _money(Decimal('0.00'), currency),  # [added]
        'items_total': _money(Decimal('0.00'), currency),  # [added]
        'grand_total': _money(Decimal(session_template['subtotal']['amount']) if session_template else Decimal('0.00'), currency),  # [added]
    }  # [added]
    return {  # [added]
        'order_id': order.pk,  # [added]
        'currency': currency,  # [added]
        'template': template_obj,  # [added]
        'services': [],  # [added]
        'items': [],  # [added]
        'totals': totals,  # [added]
        'warnings': [],  # [added]
        'errors': [],  # [added]
    }  # [added]


@require_GET  # [added]
def basket_get(request):  # [added]
    order = _get_or_create_draft_order(request.user)  # [added]
    if not order:  # [added]
        return HttpResponseForbidden('Authentication required')  # [added]
    tpl = request.session.get(SESSION_TEMPLATE_KEY)  # [added]
    return JsonResponse(_basket_from(order, tpl))  # [added]


@csrf_exempt  # [added]
@require_POST  # [added]
def template_post(request):  # [added]
    order = _get_or_create_draft_order(request.user)  # [added]
    if not order:  # [added]
        return HttpResponseForbidden('Authentication required')  # [added]
    try:  # [added]
        payload = json.loads(request.body or '{}')  # [added]
    except json.JSONDecodeError:  # [added]
        return HttpResponseBadRequest('Invalid JSON')  # [added]
    template_id = payload.get('template_id')  # [added]
    guest_count = payload.get('guest_count')  # [added]
    if not isinstance(template_id, int) or not isinstance(guest_count, int) or guest_count < 1:  # [added]
        return HttpResponseBadRequest('template_id and guest_count are required')  # [added]
    tpl = get_object_or_404(Template, pk=template_id)  # [added]

    unit, subtotal = _compute_template_pricing(tpl, guest_count)  # [added]
    template_obj = {  # [added]
        'template_id': tpl.pk,  # [added]
        'name': tpl.title,  # [added]
        'guest_count': guest_count,  # [added]
        'unit_price': _money(unit, tpl.currency),  # [added]
        'subtotal': _money(subtotal, tpl.currency),  # [added]
        'currency': tpl.currency,  # [added]
    }  # [added]

    # Persist in session for now; a future migration will store on Order.  # [added]
    request.session[SESSION_TEMPLATE_KEY] = template_obj  # [added]
    request.session.modified = True  # [added]

    # Align order currency to template currency per business rule  # [added]
    if order.currency != tpl.currency:  # [added]
        order.currency = tpl.currency  # [added]
        order.save(update_fields=['currency'])  # [added]

    return JsonResponse(_basket_from(order, template_obj))  # [added]


@csrf_exempt  # [added]
@require_POST  # [added]
def template_guests_patch(request):  # [added]
    order = _get_or_create_draft_order(request.user)  # [added]
    if not order:  # [added]
        return HttpResponseForbidden('Authentication required')  # [added]
    try:  # [added]
        payload = json.loads(request.body or '{}')  # [added]
    except json.JSONDecodeError:  # [added]
        return HttpResponseBadRequest('Invalid JSON')  # [added]
    guest_count = payload.get('guest_count')  # [added]
    tpl_state = request.session.get(SESSION_TEMPLATE_KEY)  # [added]
    if not tpl_state:  # [added]
        return HttpResponseBadRequest('No template selected')  # [added]
    if not isinstance(guest_count, int) or guest_count < 1:  # [added]
        return HttpResponseBadRequest('guest_count must be >= 1')  # [added]
    tpl = get_object_or_404(Template, pk=tpl_state['template_id'])  # [added]
    unit, subtotal = _compute_template_pricing(tpl, guest_count)  # [added]
    tpl_state['guest_count'] = guest_count  # [added]
    tpl_state['unit_price'] = _money(unit, tpl.currency)  # [added]
    tpl_state['subtotal'] = _money(subtotal, tpl.currency)  # [added]
    request.session[SESSION_TEMPLATE_KEY] = tpl_state  # [added]
    request.session.modified = True  # [added]
    return JsonResponse(_basket_from(order, tpl_state))  # [added]


# Placeholders for future add-on services/items implementation  # [added]
@csrf_exempt  # [added]
@require_POST  # [added]
def services_post(request):  # [added]
    return HttpResponseBadRequest('Not implemented yet')  # [added]


@csrf_exempt  # [added]
@require_POST  # [added]
def service_item_patch(request, service_id: int, item_id: int):  # [added]
    return HttpResponseBadRequest('Not implemented yet')  # [added]


@csrf_exempt  # [added]
@require_POST  # [added]
def items_post(request):  # [added]
    return HttpResponseBadRequest('Not implemented yet')  # [added]


@csrf_exempt  # [added]
@require_POST  # [added]
def item_patch(request, item_id: int):  # [added]
    return HttpResponseBadRequest('Not implemented yet')  # [added]


@csrf_exempt  # [added]
@require_POST  # [added]
def verify_post(request):  # [added]
    order = _get_or_create_draft_order(request.user)  # [added]
    if not order:  # [added]
        return HttpResponseForbidden('Authentication required')  # [added]
    tpl = request.session.get(SESSION_TEMPLATE_KEY)  # [added]
    # In future, perform DB revalidation; for now just echo current basket  # [added]
    return JsonResponse(_basket_from(order, tpl))  # [added]
