# Generated by Django 5.1.12 on 2025-10-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'permissions': [('can_create_agent', 'Can create agent'), ('can_edit_agent', 'Can edit agent'), ('can_delete_agent', 'Can delete agent')], 'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='users_agent_status_091767_idx',
            old_name='users_agent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='users_agent_departm_64dc18_idx',
            old_name='users_agent_department_idx',
        ),
    ]
