# Generated by Django 5.2.1 on 2025-06-01 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_professional_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Default billing address', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marketing_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Marketing communication preferences', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_currency',
            field=models.CharField(default='EUR', help_text='Preferred currency for pricing', max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(blank=True, help_text='Default shipping address', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='contact_hours',
            field=models.CharField(blank=True, help_text='Hours when the professional is available for contact', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Professional profile photo', null=True, upload_to='professional_profiles/'),
        ),
        migrations.AddField(
            model_name='professional',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from customers (1.00-5.00)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='professionalcustomerlink',
            name='last_interaction_date',
            field=models.DateTimeField(blank=True, help_text='Date of the last interaction between professional and customer', null=True),
        ),
        migrations.AddField(
            model_name='professionalcustomerlink',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this professional-customer relationship', null=True),
        ),
        migrations.AddField(
            model_name='professionalcustomerlink',
            name='preferred_communication',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('SMS', 'SMS'), ('APP', 'In-App'), ('ANY', 'Any Method')], default='EMAIL', help_text='Preferred method of communication', max_length=10),
        ),
        migrations.AddField(
            model_name='professionalcustomerlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='users_custo_company_a60cec_idx'),
        ),
        migrations.AddIndex(
            model_name='professional',
            index=models.Index(fields=['rating'], name='users_profe_rating_565c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalcustomerlink',
            index=models.Index(fields=['status'], name='users_profe_status_8d03ba_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalcustomerlink',
            index=models.Index(fields=['relationship_start_date'], name='users_profe_relatio_c7f17d_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalcustomerlink',
            index=models.Index(fields=['last_interaction_date'], name='users_profe_last_in_9136a8_idx'),
        ),
    ]
