# Generated by Django 5.1.12 on 2025-11-09 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingTimeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wedding_timeline', serialize=False, to='users.customer')),
                ('event_organiser_name', models.CharField(blank=True, help_text='Name of the event organiser', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, help_text='Event organiser contact number', max_length=20, null=True)),
                ('pre_wedding_appointment', models.DateTimeField(blank=True, help_text='Date and time of pre-wedding appointment', null=True)),
                ('location', models.CharField(blank=True, help_text='Wedding venue location', max_length=255, null=True)),
                ('apostille_stamp', models.BooleanField(default=False, help_text='Whether apostille stamp is required')),
                ('ceremony_admin', models.CharField(blank=True, help_text='Name of ceremony administrator', max_length=255, null=True)),
                ('adults', models.IntegerField(default=0, help_text='Number of adult guests')),
                ('children', models.IntegerField(default=0, help_text='Number of children guests')),
                ('babies', models.IntegerField(default=0, help_text='Number of baby guests')),
            ],
            options={
                'verbose_name': 'Wedding Timeline',
                'verbose_name_plural': 'Wedding Timelines',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='bride_contact',
            field=models.CharField(blank=True, help_text='Bride contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bride_name',
            field=models.CharField(blank=True, help_text='Full name of the bride', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact',
            field=models.TextField(blank=True, help_text='Emergency contact name and phone number', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='groom_contact',
            field=models.CharField(blank=True, help_text='Groom contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='groom_name',
            field=models.CharField(blank=True, help_text='Full name of the groom', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='planner',
            field=models.CharField(blank=True, help_text='Wedding planner or coordinator name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Special notes for the wedding', null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the professional', max_length=20, null=True),
        ),
    ]
