# Generated by Django 5.2.1 on 2025-06-08 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wedding_day',
            field=models.DateField(default=django.utils.timezone.now, help_text='The planned wedding day (must be in the future).'),
            preserve_default=False,
        ),
    ]
