# Generated by Django 5.1.12 on 2025-10-25 08:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_alter_service_description_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The starting price for the template package.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Price')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], default='EUR', help_text="The currency for the template's pricing.", max_length=3, verbose_name='Currency')),
                ('default_guests', models.PositiveIntegerField(default=0, help_text='The number of guests included in the base price. Users can adjust this.', verbose_name='Number of Guests')),
                ('price_per_additional_guest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price for each guest above the default number.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Additional Guest Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='users.professional', verbose_name='Professional')),
                ('services', models.ManyToManyField(blank=True, related_name='templates', to='services.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Main Course', 'Desserts', 'Decorations'", max_length=200, verbose_name='Group Name')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order of this group', verbose_name='Position')),
                ('mandatory_count', models.PositiveIntegerField(default=0, help_text='Number of items customer must select from this group (0 = optional)', verbose_name='Mandatory Items Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='packages.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Item Group',
                'verbose_name_plural': 'Template Item Groups',
                'ordering': ['template', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='template_images/', verbose_name='Image')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='packages.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Image',
                'verbose_name_plural': 'Template Images',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('template',), name='unique_default_image_per_template')],
            },
        ),
        migrations.CreateModel(
            name='TemplateItemGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within the group', verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.templateitemgroup', verbose_name='Group')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_group_items', to='services.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Template Group Item',
                'verbose_name_plural': 'Template Group Items',
                'ordering': ['group', 'position', 'item__title'],
                'unique_together': {('group', 'item')},
            },
        ),
    ]
