# Generated by Django 5.2.1 on 2025-06-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_item_description_alter_service_description'),
        ('services', '0002_item_max_quantity_item_min_quantity_item_quantity_and_more'),
    ]

    operations = [
    ]
