# Generated by Django 5.2.1 on 2025-06-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
