# Generated by Django 5.1.12 on 2025-10-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_merge_20250614_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='Optional description of this category', null=True),
        ),
    ]
