# Generated by Django 5.1.12 on 2025-11-08 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_alter_label_visible_to_client'),
        ('services', '0004_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['amount'], 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AddField(
            model_name='price',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Optional: Link price directly to service (bypasses item level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.service'),
        ),
        migrations.AlterField(
            model_name='price',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.item'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['item'], name='services_pr_item_id_2f89b5_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['service'], name='services_pr_service_541953_idx'),
        ),
    ]
