# Generated by Django 5.2.1 on 2025-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], default='EUR', max_length=3),
        ),
    ]
