# Generated by Django 5.2.1 on 2025-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this item currently available?'),
        ),
    ]
