# Generated by Django 5.2.1 on 2025-06-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_item_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this category', null=True),
        ),
    ]
