# Generated by Django 5.2.2 on 2025-06-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0009_service_labels_item_labels_price_labels'),
        ('users', '0006_customer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='users.professional', verbose_name='Professional')),
                ('services', models.ManyToManyField(blank=True, related_name='templates', to='services.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
