# Generated by Django 5.1.12 on 2025-10-19 12:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The starting price for the template package.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Price'),
        ),
        migrations.AddField(
            model_name='template',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar'), ('GBP', 'British Pound')], default='EUR', help_text="The currency for the template's pricing.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='template',
            name='default_guests',
            field=models.PositiveIntegerField(default=0, help_text='The number of guests included in the base price. Users can adjust this.', verbose_name='Number of Guests'),
        ),
        migrations.AddField(
            model_name='template',
            name='price_per_additional_guest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price for each guest above the default number.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Additional Guest Price'),
        ),
    ]
