# Generated by Django 5.2.2 on 2025-06-07 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='template_images/', verbose_name='Image')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='templates.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Image',
                'verbose_name_plural': 'Template Images',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('template',), name='unique_default_image_per_template')],
            },
        ),
    ]
