# Generated by Django 5.1.12 on 2025-10-19 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_description_and_more'),
        ('templates', '0002_template_base_price_template_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Main Course', 'Desserts', 'Decorations'", max_length=200, verbose_name='Group Name')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order of this group', verbose_name='Position')),
                ('mandatory_count', models.PositiveIntegerField(default=0, help_text='Number of items customer must select from this group (0 = optional)', verbose_name='Mandatory Items Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='templates.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Item Group',
                'verbose_name_plural': 'Template Item Groups',
                'ordering': ['template', 'position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItemGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, help_text='Display order within the group', verbose_name='Position')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='templates.templateitemgroup', verbose_name='Group')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_group_items', to='services.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Template Group Item',
                'verbose_name_plural': 'Template Group Items',
                'ordering': ['group', 'position', 'item__title'],
                'unique_together': {('group', 'item')},
            },
        ),
    ]
