# Generated by Django 5.1.10 on 2025-06-07 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0009_service_labels_item_labels_price_labels'),
        ('users', '0006_customer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this template currently available?')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='users.professional')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['professional', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='template_images/')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default image for the template?')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image', max_length=255)),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of this image in the template display')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='template_app.template')),
            ],
            options={
                'verbose_name': 'Template Image',
                'verbose_name_plural': 'Template Images',
                'ordering': ['template', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TemplateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0, help_text='Position of this service in the template')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_services', to='services.service')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_services', to='template_app.template')),
            ],
            options={
                'verbose_name': 'Template Service',
                'verbose_name_plural': 'Template Services',
                'ordering': ['template', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['is_active'], name='template_ap_is_acti_bfb717_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['professional', 'is_active'], name='template_ap_profess_f8e412_idx'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('professional', 'slug'), name='unique_professional_template_slug'),
        ),
        migrations.AddIndex(
            model_name='templateimage',
            index=models.Index(fields=['template', 'position'], name='template_ap_templat_0e3cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='templateimage',
            index=models.Index(fields=['is_default'], name='template_ap_is_defa_b121b7_idx'),
        ),
        migrations.AddIndex(
            model_name='templateservice',
            index=models.Index(fields=['template', 'position'], name='template_ap_templat_346ad4_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateservice',
            constraint=models.UniqueConstraint(fields=('template', 'service'), name='unique_template_service'),
        ),
    ]
