# Generated by Django 5.2.1 on 2025-06-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('label_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('PROFESSIONAL', 'Professional'), ('SERVICE', 'Service'), ('ITEM', 'Item'), ('PRICE', 'Price'), ('ORDER', 'Order')], db_index=True, default='ITEM', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of this label', null=True)),
                ('color', models.CharField(default='#CCCCCC', help_text='Hex color code for the label', max_length=7)),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['name'],
            },
        ),
    ]
