# Generated by Django 5.1.12 on 2025-10-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='visible_to_client',
            field=models.BooleanField(blank=True, default=True, help_text='Whether this label is visible to clients'),
        ),
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description of this label'),
        ),
    ]
