# Generated by Django 5.2.2 on 2025-06-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('priority', 'Priority'), ('status', 'Status'), ('custom', 'Custom')], default='general', max_length=20),
        ),
    ]
