# Generated by Django 5.1.12 on 2025-10-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_visible_to_client_alter_label_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='visible_to_client',
            field=models.BooleanField(blank=True, default=False, help_text='Whether this label is visible to clients'),
        ),
    ]
