# Generated by Django 5.2.1 on 2025-06-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_new_label_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='type',
            field=models.CharField(choices=[('professional', 'Professional Tag'), ('customer', 'Customer Tag'), ('service', 'Service Tag'), ('item', 'Item Tag'), ('price', 'Price Tag'), ('order', 'Order Tag')], default='general', max_length=20),
        ),
    ]
