# Generated by Django 5.1.10 on 2025-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_label_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='type',
        ),
        migrations.AddField(
            model_name='label',
            name='label_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PROFESSIONAL', 'Professional'), ('SERVICE', 'Service'), ('ITEM', 'Item'), ('PRICE', 'Price'), ('ORDER', 'Order')], db_index=True, default='ITEM', max_length=50),
        ),
    ]
