# Generated by Django manually

from django.db import migrations

def add_deposit_paid_label_data(apps, schema_editor):
    Label = apps.get_model('labels', 'Label')
    Label.objects.create(
        name='deposit_paid',
        label_type='CUSTOMER',  # Changed to uppercase
        color='#28a745'
    )

def remove_deposit_paid_label_data(apps, schema_editor):
    Label = apps.get_model('labels', 'Label')
    Label.objects.filter(
        name='deposit_paid',
        label_type='CUSTOMER'  # Changed to uppercase
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_remove_label_type_label_label_type'),
    ]

    operations = [
        migrations.RunPython(add_deposit_paid_label_data, reverse_code=remove_deposit_paid_label_data),
    ]
