# Generated by Django 5.2.1 on 2025-06-13 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='DISABLED', max_length=20)),
                ('labels', models.ManyToManyField(blank=True, related_name='rules', to='labels.label')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.ruletrigger')),
            ],
        ),
        migrations.CreateModel(
            name='RuleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('STATUS_CHANGE', 'Status Change')], max_length=50)),
                ('action_params', models.JSONField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rules.rule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(choices=[('CUSTOMER', 'Customer'), ('PROFESSIONAL', 'Professional'), ('SERVICE', 'Service'), ('ITEM', 'Item'), ('PRICE', 'Price'), ('ORDER', 'Order')], max_length=50)),
                ('operator', models.CharField(choices=[('HAS_LABEL', 'Has Label'), ('NOT_LABEL', 'Not Label')], max_length=20)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.label')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='rules.rule')),
            ],
        ),
    ]
