# Generated by Django 5.2.1 on 2025-06-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulecondition',
            name='entity',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PROFESSIONAL', 'Professional'), ('SERVICE', 'Service'), ('ITEM', 'Item'), ('PRICE', 'Price'), ('ORDER', 'Order')], max_length=50),
        ),
    ]
