# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agent'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent who created this order, if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_orders', to='users.agent'),
        ),
    ]

