# Generated by Django 5.1.12 on 2025-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_assigned_agent'),
        ('users', '0003_alter_agent_options_and_more'),
    ]

    operations = [
        # CHANGED: Removed duplicate assigned_agent field (already exists in migration 0004)
        migrations.AddField(
            model_name='order',
            name='couple_name',
            field=models.CharField(blank=True, help_text='Full names of the couple getting married', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wedding_day',
            field=models.DateField(blank=True, help_text="The couple's wedding day", null=True),
        ),
    ]
