# Generated by Django 5.1.12 on 2025-11-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='couple_name',
            field=models.CharField(blank=True, help_text='Full names of the couple getting married', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wedding_day',
            field=models.DateField(blank=True, help_text="The couple's wedding day", null=True),
        ),
    ]
