# Generated by Django 5.1.10 on 2025-06-10 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_add_deposit_paid_label'),
        ('orders', '0005_order_labels_orderitem_labels'),
        ('users', '0007_agent_customer_wedding_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.agent'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.customer'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('agent__isnull', True)), models.Q(('customer__isnull', True), ('agent__isnull', False)), _connector='OR'), name='order_has_one_owner_type'),
        ),
    ]
